유저 회원가입 기능
DevKor-github/BLURTING-back pull request #2
Opened 2023-10-02 09:15 UTC by dmobtxx19

PR 포함사항
- user 정보에 따라 db에 저장 (기본 정보 / 부가 정보)
- id, email, phone 중복 찾기

Todo
- character, hobby entity 수정
- random Nickname 생성
- 인증 flow와 통합

논의사항
- 성격 취미 선택 개수 및 선택지
- 지역 정보 저장 방법
- 전공 / 대학 enum 저장 여부

2023-10-04 10:40 UTC, overthestream requested changes

2023-10-04 10:40 UTC, overthestream commented on src/entities/user.entity.ts
> +@Entity('user')
entity 명을 `user` 이라고 하면 database 의 `USER` 예약어와 충돌할 수 있어서 
'user_entity'나 'users' 등의 이름을 사용하는게 좃습니다

2023-10-04 10:40 UTC, overthestream commented on src/dtos/createUser.dto.ts
> +export class CreateUserDto{
space 바 안띄워져 있음
eslint prettier 설정 잘 해주세여

2023-10-04 10:40 UTC, overthestream commented on src/common/enums/habit.enum.ts
> +export enum Habit {
`Habit`보다 뭔가 좀 더 조은 단어가 잇을것같음

2023-10-04 10:40 UTC, overthestream commented on src/common/enums/religion.enum.ts
> +export enum Religion {
피그마 보면 직접 입력도 잇는데 종교는 enum 안 쓰는 게 나을 듯 합니다

2023-10-04 10:40 UTC, overthestream commented on src/common/enums/religion.enum.ts
> +export enum Religion {
논의 필요할 것 같긴 한데, enum 쓸 거면 숫자보다 문자열로 설정하는 게 좋을 듯

2023-10-04 10:40 UTC, overthestream commented on src/common/enums/sex.enum.ts
> +    Female = 0,
얘도 뭔가 갠적으로 숫자보다 문자열이 좋음

2023-10-04 10:40 UTC, overthestream commented on src/common/enums/sexOrient.enum.ts
> +export enum SexOrient {
얘도 뭔가 갠적으로 숫자보다 문자열이 좋음

2023-10-04 10:40 UTC, overthestream commented on src/dtos/createUser.dto.ts
> +    @IsString()
dto validation error 띄울까?

2023-10-04 10:40 UTC, overthestream commented on src/entities/user.entity.ts
> +  userId: string;
근데 우리 로그인이 필요한가 ?

2023-10-04 10:40 UTC, overthestream commented on src/entities/user.entity.ts
> +  Id: number;
소문자 고고싱

2023-10-04 10:40 UTC, overthestream commented on src/entities/user.entity.ts
> +  userHash: string;
해쉬는 뭔지여쭤봐도 될까여

2023-10-04 10:40 UTC, overthestream commented on src/dtos/createUserInfo.dto.ts
> +  height: number;
여기 아래부턴 왜 IsNumber랑 IsString 같은 거 왜 없는지 물어봐도 될까여?

2023-10-04 10:40 UTC, overthestream commented on src/dtos/createUser.dto.ts
> +    @IsPhoneNumber('KR')
이거 010으로만 저장할 거면 Locale 필요 없음

2023-10-04 10:40 UTC, overthestream commented on src/entities/user.entity.ts
> +  token: string;
여기도 OneToOne 넣어줘

2023-10-04 10:40 UTC, overthestream commented on src/user/user.controller.ts
> +    this.logger.debug(UserDto);
로깅은 추후에 다시 짭시다

2023-10-04 10:40 UTC, overthestream commented on src/user/user.service.ts
> +    return await this.userRepository.save({
`save` 바로 쓰는 것보다 `create` -> `save` 사용하거나 `insert` 쓰삼

2023-10-04 10:40 UTC, overthestream commented on src/user/user.service.ts
> +    return await this.userInfoRepository.save({
이것두

2023-10-04 10:40 UTC, overthestream commented on src/user/user.service.ts
> +    const { sex, sexOrient, region, religion, drink, cigarette, height, major, mbti, character, hobby, university } = info;
근데 이러면 코드 좀 더러워지잖아요.
그래서 dto에 createEntity 같은 함수 구현해서 그거로 써도 괜찮습니다.
그러면 이제 구현은 유남쌩 알아서 하시고
const entity = info.createEntity()
await repo.save(entity)
이 느김

2023-10-04 10:40 UTC, overthestream commented on src/user/user.service.ts
> +    return user;
위에서 유저 체크하고 에러 띄우는데 user 리턴 안 해도 될 듯. 그리고 이 아래 세가지 함수가 다 똑같은 일을 하는 것 같은데, 
checkRedundantUser 이런 거로 합쳐서 하면 어떨까 싶습니다.

2023-10-04 17:56 UTC, dmobtxx19 commented on src/dtos/createUserInfo.dto.ts
> +  height: number;
아직 enum이나 자세한 설정 등등을 안해서 생략했으요

2023-10-04 17:56 UTC, dmobtxx19 commented on src/entities/user.entity.ts
> +  userHash: string;
password로 고치겟습니다^^,,

2023-10-04 17:57 UTC, kyeahxx19 commented on src/entities/user.entity.ts
> +  userId: string;
로그인 없이 어케 해요??

2023-10-06 16:49 UTC, dmobtxx19 commented on src/dtos/createUser.dto.ts
> +    @IsPhoneNumber('KR')
왜!??

2023-10-15 14:12 UTC, merged