Kyeah@refactor: auth
DevKor-github/BLURTING-back pull request #28
Opened 2024-01-27 14:08 UTC by kyeahxx19

## PR 포함 사항

-

<br>

## TODO

-

<br/>

## 논의사항

-

<br/>

## Test

-

2024-02-03 11:46 UTC, kyeahxx19 commented on src/auth/auth.service.ts
> +      where: { phoneNumber, isValid: false },
여기 왜 phoneNumber로 바뀌었

2024-02-03 11:46 UTC, kyeahxx19 commented on src/decorators/swagger/auth.decorator.ts
> +import {
파일 하나에 dto 다 넣는 게 어떤가요

2024-04-05 17:23 UTC, hyp3rflow commented on src/auth/auth.controller.ts
> +    return { refreshToken: refreshJwt, accessToken: accessJwt, id: user.id };
```suggestion
    const refreshToken = await this.authService.getRefreshToken(user.id);
    const accessToken = await this.authService.getAccessToken(user.id);
    return { refreshToken, accessToken, id: user.id };
```
매우매우사소

2024-04-05 17:23 UTC, hyp3rflow commented on src/auth/auth.service.ts
> +        phoneNumber: phoneNumber,
```suggestion
        phoneNumber,
```

2024-04-05 17:23 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +  getOppositeQueueName(queue: string): string {
타입체커가 뭐라고 안하던가요?

2024-04-05 17:23 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +    if (!question || question == null) {
```suggestion
    if (question == null) {
```
or
```suggestion
    if (!question) {
```
하고 동치일까요?

2024-04-05 17:23 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +    if (this.checkAllAnswered(questionId) && question.no / 3 !== 0) {
```javascript
question.no / 3 !== 0
```
은 `question.no`가 0일때만 true 아닌가요?

2024-04-05 17:23 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +    users.map(async (user) => {
일부러 await 안한거겠죠?

2024-04-05 17:23 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +      });
```suggestion
      .map((user) => ({
          userId: user.id,
          userNickname: user.userNickname,
          userSex: user.userInfo.sex,
          reported: reports.some(
            (report) => report.reportedUser.id === user.id,
          ),
        }));
```
사소한제취향밝히기

2024-04-05 17:23 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +      return point;
```suggestion
      return await this.pointService.giveBlurtingPoint(userId);
```
사소한제취향밝히기

2024-04-05 17:23 UTC, hyp3rflow commented on src/blurting/dtos/member.dto.ts
> +      room: room ?? null,
???

2024-04-08 12:57 UTC, kyeahxx19 commented on src/blurting/blurting.service.ts
> +  getOppositeQueueName(queue: string): string {
타입체커가... 뭐라고 해야 하나요...?

2024-04-08 12:59 UTC, kyeahxx19 commented on src/blurting/blurting.service.ts
> +    if (!question || question == null) {
null이랑 undefined 중에서 뭐가 나올지 모르겠어서 했는데... !question만 해도 될까요

2024-04-08 13:09 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +    if (!question || question == null) {
`!null`, `!undefined` 둘다 `true`에요

2024-04-08 13:11 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +  getOppositeQueueName(queue: string): string {
`queue`가 문자열인데 male도 female도 아니면 `undefined`가 반환되지 않을까요?

2024-04-11 09:00 UTC, overthestream requested changes

2024-04-11 09:00 UTC, overthestream commented on src/auth/auth.service.ts
> +      phoneNumber: phoneNumber,
```suggestion
      phoneNumber,
```

2024-04-11 09:00 UTC, overthestream commented on src/blurting/dtos/member.dto.ts
> +      room: room ?? null,
근데 저 이거 궁금한게 constructor 말고 ToDto static function 쓰는 이유가 있나요?

2024-04-11 09:00 UTC, overthestream commented on src/repositories/blurtingAnswer.repository.ts
> +      postedAt: new Date(new Date().getTime() + 9 * 60 * 60 * 1000),
이거 date 함수들 따로 빼놨는데 그거 쓰자

2024-04-12 12:15 UTC, kyeahxx19 commented on src/blurting/dtos/member.dto.ts
> +      room: room ?? null,
... constructor를 어케 쓰는 건가요, 전 저 방법밖에 몰랏어요

2024-04-12 14:36 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +    if (!groupQueue) {
타입 작성이 잘못된 것 같아요. `number[]`이 사실이라면 항상 201번 조건문을 타서는 안돼요.

2024-04-12 14:36 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +    if (!groupQueue) {
cacheManager에서 들고오는 모든 부분이 이렇게 작성된 것 같은데 고쳐야 할 것 같네요.

2024-04-12 14:36 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +          await this.cacheManager.set(qName, groupQueue.slice(5));
제가 이해하기로는 cacheManager를 이용해서 매칭을 시도하는 것 같은데 동시성 문제는 없을까요?

2024-04-12 14:36 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
> +        }
이런 부분은 cacheManager의 인터페이스를 수정하거나 추상화해서 반복되지 않도록 하는게 좋아보여요.

2024-04-12 14:36 UTC, hyp3rflow commented on src/blurting/blurting.service.ts
>      const finalRecieves = arrowDtos.iReceived;
typo

2024-04-13 09:32 UTC, hyp3rflow commented on src/blurting/dtos/member.dto.ts
> +      room: room ?? null,
제가 궁금했던건 room의 타입이긴 했어요

2024-06-04 12:22 UTC, merged